### ISSUE TITLE
Invalid instructions in pyproject.toml

### ISSUE THREAD

**Issue by danoan** [danoan/journal-manager#1]
There is an error in the pyproject.toml file

It should be `tool` and not `tools`.

The instructions below are not having any effect:
```toml
[tools.setuptools]
include-package-data = true

[tools.setuptools.package-data]
"danoan.journal_manager.templates"=["*.txt"]
```

That's why I still need the MANIFEST.in in order to have data
files being exported.

I should update the pyproject.toml and remove the MANIFEST.in
